# Generated by Django 4.1.7 on 2023-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userfilmrelation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilmrelation',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
