# Generated by Django 4.1.7 on 2023-03-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userfilmrelation_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilmrelation',
            name='comment',
        ),
    ]
