# Generated by Django 4.1.7 on 2023-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userfilmrelation_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfilmrelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
